name: " Bug report"
description: "Reporta un problema reproducible"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar el problema.
        Incluye la mayor cantidad de contexto posible para poder reproducirlo.

  - type: textarea
    id: summary
    attributes:
      label: "Descripci贸n"
      description: "驴Qu茅 pas贸 y qu茅 esperabas que pase?"
      placeholder: "Descripci贸n clara y concisa del bug."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducir"
      description: "Lista de pasos m铆nimos para reproducir el problema."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Resultado esperado"
      placeholder: "Qu茅 deber铆a haber ocurrido."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Resultado actual"
      placeholder: "Qu茅 ocurri贸 realmente (incluye logs si aplica)."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Versi贸n"
      description: "Versi贸n del proyecto (tag/commit) o despliegue (URL)."
      placeholder: "commit abc123 / https://<tu-app>.vercel.app"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "Sistema operativo"
      options:
        - "Windows"
        - "Linux"
        - "macOS"
        - "Otro"
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: "Entorno"
      description: "Incluye Node (si aplica), navegador y cualquier detalle relevante."
      placeholder: |
        - Node: 20.x (si aplica)
        - Navegador: Chrome/Edge/Firefox + versi贸n
        - Instalaci贸n: npm
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Logs / salida de error"
      description: "Pega aqu铆 la salida relevante."
      render: shell
    validations:
      required: false
